version: '3.8'

services: 

    app:
        build: .
        container_name: flask-app
        ports:
            - 7000:7000 # 7000 -> 7000
        volumes:
          - .:/app
        #environment: 
        #  - SQL_CONECTION="mysql+pymysql://root:root@localhost:8889/products_db"
        command: python /app/src/app.py

  